### ISSUE TITLE
关于第九周kaggle汇报

### ISSUE THREAD

**Issue by dugzzuli** [wangjin0818/Artificial_Intelligence#1]
王老师，汇报kaggle上面的题目，是自己做ppt啊？还是我们用您的那张海报？

**Comment by wangjin0818** [comment]
是一个proposal，类似于开题报告，是要用PPT说明你所做的问题，以及这个问题的难点在哪里，解决问题的思路和拟使用的方法等，重点在于开题，而不是最终的结果。海报和结题报告会在期末进行。
